# Usar la imagen base de Ubuntu
FROM ubuntu:latest

# Actualizar el sistema e instalar dependencias
RUN apt-get update && apt-get install -y wget gnupg2 lsb-release

# Agregar el repositorio oficial de PostgreSQL para la versión 15
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list

# Importar la clave del repositorio de PostgreSQL y agregarla al sistema
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | tee /etc/apt/trusted.gpg.d/pgdg.asc

# Instalar PostgreSQL 15.7
RUN apt-get update && apt-get install -y postgresql-15

# Configurar PostgreSQL para escuchar en todas las interfaces
RUN echo "listen_addresses='*'" >> /etc/postgresql/15/main/postgresql.conf

# Establecer una contraseña para el usuario 'postgres'
RUN service postgresql start && \
    su - postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'postgres_password';\""

# Crear un usuario adicional de PostgreSQL y una base de datos
RUN service postgresql start && \
    su - postgres -c "psql -c \"CREATE USER mi_usuario WITH PASSWORD 'mi_password';\"" && \
    su - postgres -c "psql -c \"CREATE DATABASE mi_basededatos;\"" && \
    su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE mi_basededatos TO mi_usuario;\""

# Exponer el puerto 5432 para PostgreSQL
EXPOSE 5432

# Ejecutar PostgreSQL como el usuario postgres
USER postgres
CMD ["/usr/lib/postgresql/15/bin/postgres", "-D", "/var/lib/postgresql/15/main", "-c", "config_file=/etc/postgresql/15/main/postgresql.conf"]
