# Utilizamos una imagen base de Ubuntu
FROM ubuntu:latest

# Actualizar paquetes e instalar Apache, PostgreSQL y SSH
RUN apt-get update && \
    apt-get install -y apache2 postgresql postgresql-contrib openssh-server sudo && \
    apt-get clean

# Copiar el archivo index.html a la carpeta de Apache
COPY index.html /var/www/html/index.html

# Configurar Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN mkdir -p /var/run/apache2
EXPOSE 80

# Configurar PostgreSQL
RUN service postgresql start && \
    sudo -u postgres psql -c "CREATE USER docker WITH PASSWORD 'docker';" && \
    sudo -u postgres psql -c "ALTER USER docker WITH SUPERUSER;" && \
    sudo -u postgres psql -c "CREATE DATABASE docker_db;" && \
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE docker_db TO docker;"
EXPOSE 5432

# Configurar SSH
RUN mkdir /var/run/sshd
RUN echo 'root:rootpassword' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
EXPOSE 22

# Comando de inicio que arranca Apache, PostgreSQL y SSH en un solo contenedor
CMD service apache2 start && service postgresql start && service ssh start && tail -F /dev/null
