apiVersion: v1
kind: Service
metadata:
  name: aws-info-service
  namespace: aws-info
spec:
  type: LoadBalancer
  selector:
    app: aws-info
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
