apiVersion: v1
kind: Service
metadata:
  name: grupo14-service
  namespace: grupo14
spec:
  type: LoadBalancer
  selector:
    app: grupo14
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
